spring:
  application:
    name: books-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/books_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true